---
particleCount: 2000
smoothRadius: 0.35
targetDensity: 55
pressureMultiplier: 500
nearPressureMultiplier: 0
viscosityMultiplier: 0.06
boundaryMultipler: 50000.0
gravityAccValue: 9.8
dataScale: 0.01
rangeForceScale: 5000
rangeForceRadius: 2.0

startPoint:
  - 4
  - 1
stride: 0.1
maxWidth: 4
randomize: no