---
particleCount: 512
smoothRadius: 0.35
collisionDamping: 0.5
targetDensity: 10
pressureMultiplier: 50
gravityAccValue: 12
dataScale: 0.01
externalForceScale: 1000.0
externalForceRadius: 1.5

startPoint:
  - 400
  - 200
stride: 10
maxWidth: 400
randomize: yes